const char* UIERROR_CSS_PARSE_STATE_NOT_SELECTOR = "parse state is not UI_PARSE_STATE_SELECTOR";
const char* UIERROR_CSS_PARSE_STATE_NOT_CSS_DECLARATION_KEY = "parse state is not UI_PARSE_STATE_CSS_DECLARATION_KEY";
const char* UIERROR_CSS_PARSE_STATE_NOT_CSS_DECLARATION_VALUE = "parse state is not UI_PARSE_STATE_CSS_DECLARATION_VALUE";
